import fs from "fs/promises";
import path from "path";
import { prisma } from "@/lib/db";
import { ami } from "./ami";
import { addLog } from "./logs";

// Ported from the prototype's writePjsipAgents()/writeAgentHints()/
// reloadAsterisk(). Generates the PJSIP config for human-agent SIP
// extensions (used for live call transfer/handoff) from the AgentExtension
// table instead of a single in-memory settings.agents array, and reloads
// Asterisk over AMI so changes take effect immediately.

const ETC_PATH = process.env.ASTERISK_ETC_PATH || "/asterisk-etc";

export async function writeAgentConfigs() {
  const agents = await prisma.agentExtension.findMany();

  const pjsipLines = ["; Auto-generated by Ivay dialer — do not edit manually\n"];
  const hintLines = ["; Auto-generated by Ivay dialer — do not edit manually\n[hints]"];

  for (const a of agents) {
    pjsipLines.push(
      `[${a.extension}]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
auth=${a.extension}
aors=${a.extension}
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
[${a.extension}]
type=auth
auth_type=userpass
username=${a.extension}
password=${a.password}
[${a.extension}]
type=aor
max_contacts=1
qualify_frequency=0
remove_existing=yes
`
    );
    hintLines.push(`exten => ${a.extension},hint,PJSIP/${a.extension}`);
  }

  await fs.mkdir(ETC_PATH, { recursive: true });
  await fs.writeFile(path.join(ETC_PATH, "pjsip_agents.conf"), pjsipLines.join("\n"));
  await fs.writeFile(path.join(ETC_PATH, "agents_hints.conf"), hintLines.join("\n") + "\n");
}

export function reloadAsterisk(): Promise<void> {
  return new Promise((resolve) => {
    ami.action({ action: "Command", command: "module reload res_pjsip" }, () => {
      ami.action({ action: "Command", command: "dialplan reload" }, () => {
        addLog("info", "Asterisk reloaded (pjsip + dialplan)");
        resolve();
      });
    });
  });
}
